version: '3.8'

services:
  db:
    profiles:
      - "db"
      - "full"
    container_name: postgres-server
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ktor-bank
    networks:
      - my-network
    ports:
      - 5432:5432
    volumes:
      - my-volume-postgresdb:/var/lib/postgresql/data

volumes:
  my-volume-postgresdb:

networks:
  my-network:
    name: my-network